# Copyright 2021 The k8gb Contributors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
GOLIC_VERSION  ?= v0.5.0

# check integrity
.PHONY: check
check: lint license test ## Check project integrity

# run glonag-ci
.PHONY: lint
lint:
	golangci-lint run

# updates source code with license headers
.PHONY: license
license:
	$(call golic,-t apache2)

# run tests
.PHONY: test
test:
	go test ./... -coverprofile cover.out

define golic
	@go install github.com/AbsaOSS/golic@$(GOLIC_VERSION)
	$(GOBIN)/golic inject $1
endef
